In [ ]:
from google.colab import files
uploaded=files.upload()

Saving titanic.zip to titanic.zip

In [ ]:
# @title AI prompt cell

import ipywidgets as widgets
from IPython.display import display, HTML, Markdown,clear_output
from google.colab import ai

dropdown = widgets.Dropdown(
    options=[],
    layout={'width': 'auto'}
)

def update_model_list(new_options):
    dropdown.options = new_options
update_model_list(ai.list_models())

text_input = widgets.Textarea(
    placeholder='Ask me anything....',
    layout={'width': 'auto', 'height': '100px'},
)

button = widgets.Button(
    description='Submit Text',
    disabled=False,
    tooltip='Click to submit the text',
    icon='check'
)

output_area = widgets.Output(
     layout={'width': 'auto', 'max_height': '300px','overflow_y': 'scroll'}
)

def on_button_clicked(b):
    with output_area:
        output_area.clear_output(wait=False)
        accumulated_content = ""
        for new_chunk in ai.generate_text(prompt=text_input.value, model_name=dropdown.value, stream=True):
            if new_chunk is None:
                continue
            accumulated_content += new_chunk
            clear_output(wait=True)
            display(Markdown(accumulated_content))

button.on_click(on_button_clicked)
vbox = widgets.GridBox([dropdown, text_input, button, output_area])

display(HTML("""
<style>
.widget-dropdown select {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
.widget-textarea textarea {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
</style>
"""))
display(vbox)

In [ ]:
import zipfile

with zipfile.ZipFile('titanic.zip', 'r') as zip_ref:
    zip_ref.extractall()

print("Files extracted successfully!")

Files extracted successfully!

In [ ]:
import os

print(os.listdir())

['.config', 'train.csv', 'titanic.zip', 'gender_submission.csv', 'test.csv', 'sample_data']

In [ ]:
import pandas as pd
df=pd.read_csv("train.csv")
df.head()
print("Shape:",df.shape)
df.info()
df.isnull().sum()

Shape: (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])
df["Cabin"]=df["Cabin"].fillna("Unknown")

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
print("Duplicate Rows:",df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
df=df.drop_duplicates()
print("New Shape:",df.shape)

New Shape: (891, 12)

In [ ]:
df.rename(columns={
    "Passenger Id":"Passenger_ID",
    "Pclass":"Passenger_Class",
    "Sex":"Gender",
    "SibSp":"Siblings_Spouses",
    "Parch":"Parents_Children",
    "Fare":"Ticket_Fare"
},inplace=True)
df.head()

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,Siblings_Spouses,Parents_Children,Ticket,Ticket_Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

In [ ]:
df.dtypes

PassengerId           int64
Survived              int64
Passenger_Class       int64
Name                 object
Gender               object
Age                 float64
Siblings_Spouses      int64
Parents_Children      int64
Ticket               object
Ticket_Fare         float64
Cabin                object
Embarked             object
dtype: object

In [ ]:
df["Survived"] = df["Survived"].astype("category")
df["Passenger_Class"] = df["Passenger_Class"].astype("category")
df["Gender"] = df["Gender"].astype("category")

df.dtypes

PassengerId            int64
Survived            category
Passenger_Class     category
Name                  object
Gender              category
Age                  float64
Siblings_Spouses       int64
Parents_Children       int64
Ticket                object
Ticket_Fare          float64
Cabin                 object
Embarked              object
dtype: object

In [ ]:
df.to_csv("Titanic_Cleaned.csv", index=False)

print("Titanic_Cleaned.csv has been saved successfully!")

Titanic_Cleaned.csv has been saved successfully!